language: node_js

sudo: false

branches:
  only:
  - master

cache:
  - npm

node_js:
  - "stable"

install:
  - npm install

script:
  - hexo clean 
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUBTOKEN
  local-dir: public
  keep-history: false
  on:
    branch: master