# Header
menu:
  Home: /
  Security: /security
  About: /about
rss: /atom.xml

# User Info
user_name: John.W
user_avatar: https://raw.githubusercontent.com/01x01/github-blog/master/source/img/avatar.jpg
user_location: Earth
user_description: "打工是不可能打工的，做生意又不会。"
user_contact: thinkingandcoding@gmail.com
user_introduction: 

github_username: 01x01
twitter_username: 
weibo_username:
zhihu_username: 
facebook_username:
linkedin_username:

# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: true
livere_uid: 

use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

# Miscellaneous
google_analytics:
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:

# Highlight code
# do ensure u have closed all the highlight choices in ur root _config.yml
# currently we provided 6 choices based on highlight script
# highlight_default, highlight_light, highlight_github, highlight_rainbow, highlight_vs, highlight_atom
block_highlight: highlight_github
